from .__Gender import Gender
from .__DocumentType import DocumentType
from .__BloodType import BloodType
from .__ConsultationStatus import ConsultationStatus
from .__Severity import Severity
from .__DiagnosisType import DiagnosisType
from .__TreatmentType import TreatmentType
from .__TreatmentStatus import TreatmentStatus
from .__EventType import EventType
